/**
 * This component was set up to map a list of preview images to their respective items.
 * The arrays are generated using /scripts/dye-files.js.
 */

import { Component, inject } from '@angular/core';
import { IItem } from '@app/interfaces/item.interface';
import { ItemClickEvent, ItemsComponent } from '@app/components/items/items.component';
import { ItemIconComponent } from '@app/components/items/item-icon/item-icon.component';
import { DataService } from '@app/services/data.service';

const fileNames = [
  "/assets/game/dyes/2slots_Feast_yetigoggles.jpg",
  "/assets/game/dyes/2slots_Remembrance_ultsash.jpg",
  "/assets/game/dyes/Feast_scarf.jpg",
  "/assets/game/dyes/Feast_yetigoggles.jpg",
  "/assets/game/dyes/Mischief_sticker.jpg",
  "/assets/game/dyes/Moments_ultglasses.jpg",
  "/assets/game/dyes/Nature_Riverscarf.jpg",
  "/assets/game/dyes/Nature_shellnecklace.jpg",
  "/assets/game/dyes/Remembrance_childscarf.jpg",
  "/assets/game/dyes/Remembrance_ultsash.jpg",
  "/assets/game/dyes/cape/2slots_Abyss_boat.jpg",
  "/assets/game/dyes/cape/2slots_Abyss_CannoneerCape.jpg",
  "/assets/game/dyes/cape/2slots_Abyss_ult.jpg",
  "/assets/game/dyes/cape/2slots_Belonging_CousinCape.jpg",
  "/assets/game/dyes/cape/2slots_Belonging_GrandpaCape.jpg",
  "/assets/game/dyes/cape/2slots_Belonging_PleafulCape.jpg",
  "/assets/game/dyes/cape/2slots_Bloom_rosecape.jpg",
  "/assets/game/dyes/cape/2slots_Color_DarkRainbowCape.jpg",
  "/assets/game/dyes/cape/2slots_Duets_cellist.jpg",
  "/assets/game/dyes/cape/2slots_Duets_pianist.jpg",
  "/assets/game/dyes/cape/2slots_Enchantment_alchemist.jpg",
  "/assets/game/dyes/cape/2slots_Enchantment_playfight.jpg",
  "/assets/game/dyes/cape/2slots_Enchantment_snooze.jpg",
  "/assets/game/dyes/cape/2slots_Feast_WinterAncestorCape.jpg",
  "/assets/game/dyes/cape/2slots_Feast_YetiCape.jpg",
  "/assets/game/dyes/cape/2slots_Flight_NaviCape.jpg",
  "/assets/game/dyes/cape/2slots_Fortune_SnekCape.jpg",
  "/assets/game/dyes/cape/2slots_Gratitude_dismiss.jpg",
  "/assets/game/dyes/cape/2slots_Lightseeker_piggyback.jpg",
  "/assets/game/dyes/cape/2slots_Lightseeker_SLS.jpg",
  "/assets/game/dyes/cape/2slots_Moments_RangerCape.jpg",
  "/assets/game/dyes/cape/2slots_Nesting_cape.jpg",
  "/assets/game/dyes/cape/2slots_Passage_CoatCape.jpg",
  "/assets/game/dyes/cape/2slots_Performance_storyteller.jpg",
  "/assets/game/dyes/cape/2slots_Prophecy_BatCape.jpg",
  "/assets/game/dyes/cape/2slots_Prophecy_SpiderCape.jpg",
  "/assets/game/dyes/cape/2slots_Radiance_fork.jpg",
  "/assets/game/dyes/cape/2slots_Radiance_star.jpg",
  "/assets/game/dyes/cape/2slots_Radiance_ult.jpg",
  "/assets/game/dyes/cape/2slots_Radiance_X.jpg",
  "/assets/game/dyes/cape/2slots_Remembrance_tiptoe.jpg",
  "/assets/game/dyes/cape/2slots_Remembrance_vet.jpg",
  "/assets/game/dyes/cape/2slots_Revival_GratCape.jpg",
  "/assets/game/dyes/cape/2slots_Revival_RhythmCape.jpg",
  "/assets/game/dyes/cape/2slots_Sanctuary_shell.jpg",
  "/assets/game/dyes/cape/2slots_Sunlight_manta.jpg",
  "/assets/game/dyes/cape/Abyss_AnglerCape.jpg",
  "/assets/game/dyes/cape/Abyss_boat.jpg",
  "/assets/game/dyes/cape/Abyss_CannoneerCape.jpg",
  "/assets/game/dyes/cape/Abyss_cease.jpg",
  "/assets/game/dyes/cape/Abyss_ult.jpg",
  "/assets/game/dyes/cape/Assembly_student.jpg",
  "/assets/game/dyes/cape/Assembly_ult.jpg",
  "/assets/game/dyes/cape/Base_black.jpg",
  "/assets/game/dyes/cape/Base_black2.jpg",
  "/assets/game/dyes/cape/Base_blue.jpg",
  "/assets/game/dyes/cape/Base_blue2.jpg",
  "/assets/game/dyes/cape/Base_green.jpg",
  "/assets/game/dyes/cape/Base_green2.jpg",
  "/assets/game/dyes/cape/Base_moth.jpg",
  "/assets/game/dyes/cape/Base_pink.jpg",
  "/assets/game/dyes/cape/Base_pink2.jpg",
  "/assets/game/dyes/cape/Base_purple.jpg",
  "/assets/game/dyes/cape/Base_purple2.jpg",
  "/assets/game/dyes/cape/Base_red.jpg",
  "/assets/game/dyes/cape/Base_red2.jpg",
  "/assets/game/dyes/cape/Base_teal.jpg",
  "/assets/game/dyes/cape/Base_teal2.jpg",
  "/assets/game/dyes/cape/Base_white.jpg",
  "/assets/game/dyes/cape/Base_white2.jpg",
  "/assets/game/dyes/cape/Base_yellow.jpg",
  "/assets/game/dyes/cape/Base_yellow2.jpg",
  "/assets/game/dyes/cape/Belonging_CousinCape.jpg",
  "/assets/game/dyes/cape/Belonging_GrandpaCape.jpg",
  "/assets/game/dyes/cape/Belonging_PleafulCape.jpg",
  "/assets/game/dyes/cape/Bloom_rosecape.jpg",
  "/assets/game/dyes/cape/Color_DarkRainbowCape.jpg",
  "/assets/game/dyes/cape/Dreams_DP.jpg",
  "/assets/game/dyes/cape/Dreams_peek.jpg",
  "/assets/game/dyes/cape/Dreams_spin.jpg",
  "/assets/game/dyes/cape/Dreams_ult.jpg",
  "/assets/game/dyes/cape/Duets_cellist.jpg",
  "/assets/game/dyes/cape/Duets_pianist.jpg",
  "/assets/game/dyes/cape/Enchantment_alchemist.jpg",
  "/assets/game/dyes/cape/Enchantment_crabwalk.jpg",
  "/assets/game/dyes/cape/Enchantment_playfight.jpg",
  "/assets/game/dyes/cape/Enchantment_snooze.jpg",
  "/assets/game/dyes/cape/Feast_peek.jpg",
  "/assets/game/dyes/cape/Feast_santa.jpg",
  "/assets/game/dyes/cape/Feast_SnowflakeCape.jpg",
  "/assets/game/dyes/cape/Feast_WinterAncestorCape.jpg",
  "/assets/game/dyes/cape/Feast_YetiCape.jpg",
  "/assets/game/dyes/cape/Flight_LWCape.jpg",
  "/assets/game/dyes/cape/Flight_NaviCape.jpg",
  "/assets/game/dyes/cape/Fortune_DragonCape.jpg",
  "/assets/game/dyes/cape/Fortune_SnekCape.jpg",
  "/assets/game/dyes/cape/Gratitude_dismiss.jpg",
  "/assets/game/dyes/cape/Gratitude_yoga.jpg",
  "/assets/game/dyes/cape/Lightseeker_CrabCallCape.jpg",
  "/assets/game/dyes/cape/Lightseeker_piggyback.jpg",
  "/assets/game/dyes/cape/Lightseeker_SLS.jpg",
  "/assets/game/dyes/cape/Mischef_crabulacape.webp",
  "/assets/game/dyes/cape/Mischief_BatCape.jpg",
  "/assets/game/dyes/cape/Mischief_cat.jpg",
  "/assets/game/dyes/cape/Mischief_SpiderCape.jpg",
  "/assets/game/dyes/cape/Moments_RangerCape.jpg",
  "/assets/game/dyes/cape/Music_cape.jpg",
  "/assets/game/dyes/cape/Nature_ocean.jpg",
  "/assets/game/dyes/cape/Nesting_cape.jpg",
  "/assets/game/dyes/cape/Passage_CoatCape.jpg",
  "/assets/game/dyes/cape/Passage_RacoonCape.jpg",
  "/assets/game/dyes/cape/Performance_mellow.jpg",
  "/assets/game/dyes/cape/Performance_storyteller.jpg",
  "/assets/game/dyes/cape/Performance_ult.jpg",
  "/assets/game/dyes/cape/Prophecy_BatCape.jpg",
  "/assets/game/dyes/cape/Prophecy_SpiderCape.jpg",
  "/assets/game/dyes/cape/Prophecy_TurtleCape.jpg",
  "/assets/game/dyes/cape/Radiance_fork.jpg",
  "/assets/game/dyes/cape/Radiance_star.jpg",
  "/assets/game/dyes/cape/Radiance_ult.jpg",
  "/assets/game/dyes/cape/Radiance_X.jpg",
  "/assets/game/dyes/cape/Remembrance_tiptoe.jpg",
  "/assets/game/dyes/cape/Remembrance_vet.jpg",
  "/assets/game/dyes/cape/Remembrance_WarriorCape.jpg",
  "/assets/game/dyes/cape/Revival_AbyssCape.jpg",
  "/assets/game/dyes/cape/Revival_EnchantCape.jpg",
  "/assets/game/dyes/cape/Revival_GratCape.jpg",
  "/assets/game/dyes/cape/Revival_RhythmCape.jpg",
  "/assets/game/dyes/cape/Rhythm_juggler.jpg",
  "/assets/game/dyes/cape/Sanctuary_chill.jpg",
  "/assets/game/dyes/cape/Sanctuary_shell.jpg",
  "/assets/game/dyes/cape/Sanctuary_TimidCape.jpg",
  "/assets/game/dyes/cape/Sunlight_manta.jpg",
  "/assets/game/dyes/hair/2slots_Bloom_rosebraid.jpg",
  "/assets/game/dyes/hair/Bloom_rosebraid.jpg",
  "/assets/game/dyes/hair/Radiance_Greeting.jpg",
  "/assets/game/dyes/hair-accessory/2slots_Moments_rangerhat.jpg",
  "/assets/game/dyes/hair-accessory/Belonging_earmuffs.jpg",
  "/assets/game/dyes/hair-accessory/Flight_chimefeather.jpg",
  "/assets/game/dyes/hair-accessory/Flight_navifeathers.jpg",
  "/assets/game/dyes/hair-accessory/Flight_ultfeathers.jpg",
  "/assets/game/dyes/hair-accessory/Fortune_fish.jpg",
  "/assets/game/dyes/hair-accessory/Love_flowercrown.jpg",
  "/assets/game/dyes/hair-accessory/Moments_rangerhat.jpg",
  "/assets/game/dyes/hair-accessory/Moments_ulthat.jpg",
  "/assets/game/dyes/hair-accessory/Nesting_pencil.jpg",
  "/assets/game/dyes/hair-accessory/Radiance_Greeting.jpg",
  "/assets/game/dyes/hair-accessory/Revival_bow.jpg",
  "/assets/game/dyes/hair-accessory/Sanctuary_chillhat.jpg",
  "/assets/game/dyes/hair-accessory/Style_tophat.jpg",
  "/assets/game/dyes/hair-accessory/Style_veil.jpg",
  "/assets/game/dyes/hair-accessory/Sunlight_hat.jpg",
  "/assets/game/dyes/head-accessory/2slots_Passage_tassels.jpg",
  "/assets/game/dyes/head-accessory/Dreams_yetihorns.jpg",
  "/assets/game/dyes/head-accessory/Enchantment_ulttassels.jpg",
  "/assets/game/dyes/head-accessory/Feast_antlers.jpg",
  "/assets/game/dyes/head-accessory/Fortune_dragonearrings.jpg",
  "/assets/game/dyes/head-accessory/Passage_tassels.jpg",
  "/assets/game/dyes/head-accessory/Radiance_Provoking.jpg",
  "/assets/game/dyes/head-accessory/Revival_earrings.jpg",
  "/assets/game/dyes/mask/2slots_Abyss_Cease.jpg",
  "/assets/game/dyes/mask/2slots_Abyss_f2p.jpg",
  "/assets/game/dyes/mask/2slots_Abyss_ult.jpg",
  "/assets/game/dyes/mask/2slots_Base_mask.jpg",
  "/assets/game/dyes/mask/2slots_Bloom_rosemask.jpg",
  "/assets/game/dyes/mask/2slots_Colour_mask.jpg",
  "/assets/game/dyes/mask/2slots_Fortune_blush.jpg",
  "/assets/game/dyes/mask/2slots_Gratitude_ult.jpg",
  "/assets/game/dyes/mask/2slots_Love_rose.jpg",
  "/assets/game/dyes/mask/2slots_Mischief_cat.jpg",
  "/assets/game/dyes/mask/2slots_Performance_ult.jpg",
  "/assets/game/dyes/mask/2slots_Radiance_ult.jpg",
  "/assets/game/dyes/mask/2slots_Treasure_mask.jpg",
  "/assets/game/dyes/mask/Abyss_Cease.jpg",
  "/assets/game/dyes/mask/Abyss_f2p.jpg",
  "/assets/game/dyes/mask/Abyss_ult.jpg",
  "/assets/game/dyes/mask/Assembly_botanist.jpg",
  "/assets/game/dyes/mask/Assembly_cadet.jpg",
  "/assets/game/dyes/mask/Assembly_chuckle.jpg",
  "/assets/game/dyes/mask/Assembly_daydream.jpg",
  "/assets/game/dyes/mask/Assembly_march.jpg",
  "/assets/game/dyes/mask/Assembly_student.jpg",
  "/assets/game/dyes/mask/Assembly_ult.jpg",
  "/assets/game/dyes/mask/Base_chibi.jpg",
  "/assets/game/dyes/mask/Base_default.jpg",
  "/assets/game/dyes/mask/Base_mask.jpg",
  "/assets/game/dyes/mask/Bloom_rosemask.jpg",
  "/assets/game/dyes/mask/Colour_mask.jpg",
  "/assets/game/dyes/mask/Dreams_DP.jpg",
  "/assets/game/dyes/mask/Dreams_peek.jpg",
  "/assets/game/dyes/mask/Dreams_quail.jpg",
  "/assets/game/dyes/mask/Dreams_ult2.jpg",
  "/assets/game/dyes/mask/Duets_seahorse.jpg",
  "/assets/game/dyes/mask/Enchantment_muralist.jpg",
  "/assets/game/dyes/mask/Enchantment_playfight.jpg",
  "/assets/game/dyes/mask/Enchantment_scarecrow.jpg",
  "/assets/game/dyes/mask/Fortune_blush.jpg",
  "/assets/game/dyes/mask/Fortune_bull.jpg",
  "/assets/game/dyes/mask/Fortune_dragon.jpg",
  "/assets/game/dyes/mask/Fortune_rabbit.jpg",
  "/assets/game/dyes/mask/Fortune_snake.jpg",
  "/assets/game/dyes/mask/Fortune_tiger.jpg",
  "/assets/game/dyes/mask/Gratitude_dismiss.jpg",
  "/assets/game/dyes/mask/Gratitude_Leap.jpg",
  "/assets/game/dyes/mask/Gratitude_Provoke.jpg",
  "/assets/game/dyes/mask/Gratitude_Sassy.jpg",
  "/assets/game/dyes/mask/Gratitude_Shaman.jpg",
  "/assets/game/dyes/mask/Gratitude_ult.webp",
  "/assets/game/dyes/mask/Lightseeker_crab.jpg",
  "/assets/game/dyes/mask/Lightseeker_doublefive.jpg",
  "/assets/game/dyes/mask/Lightseeker_laidback.jpg",
  "/assets/game/dyes/mask/Lightseeker_piggyback.jpg",
  "/assets/game/dyes/mask/Lightseeker_SLS.jpg",
  "/assets/game/dyes/mask/Lightseeker_Twirl.jpg",
  "/assets/game/dyes/mask/Love_rose.jpg",
  "/assets/game/dyes/mask/Mischief_cat.jpg",
  "/assets/game/dyes/mask/Moments_blindfold.jpg",
  "/assets/game/dyes/mask/Moments_ranger.jpg",
  "/assets/game/dyes/mask/Nature_river.jpg",
  "/assets/game/dyes/mask/Passage_boar.jpg",
  "/assets/game/dyes/mask/Passage_guidebear.jpg",
  "/assets/game/dyes/mask/Passage_monke.jpg",
  "/assets/game/dyes/mask/Passage_racooon.jpg",
  "/assets/game/dyes/mask/Passage_serow.jpg",
  "/assets/game/dyes/mask/Performance_ult.jpg",
  "/assets/game/dyes/mask/Prophecy_bat.jpg",
  "/assets/game/dyes/mask/Prophecy_lion.jpg",
  "/assets/game/dyes/mask/Prophecy_spider.jpg",
  "/assets/game/dyes/mask/Prophecy_turtle.jpg",
  "/assets/game/dyes/mask/Prophecy_ultmask.webp",
  "/assets/game/dyes/mask/Radiance_ult.jpg",
  "/assets/game/dyes/mask/Remembrance_Veteran.jpg",
  "/assets/game/dyes/mask/Style_sparkle.jpg",
  "/assets/game/dyes/mask/Treasure_mask.jpg",
  "/assets/game/dyes/outfit/2slots_Abyss_angler.jpg",
  "/assets/game/dyes/outfit/2slots_Assembly_chuckle.jpg",
  "/assets/game/dyes/outfit/2slots_Belonging_kid.jpg",
  "/assets/game/dyes/outfit/2slots_Bloom_gardener.jpg",
  "/assets/game/dyes/outfit/2slots_Color_DarkRainbowTunic.jpg",
  "/assets/game/dyes/outfit/2slots_Color_GaySuspenders.jpg",
  "/assets/game/dyes/outfit/2slots_Dreams_Yeti.jpg",
  "/assets/game/dyes/outfit/2slots_Duets_Cellist1.jpg",
  "/assets/game/dyes/outfit/2slots_Duets_Cellist2.jpg",
  "/assets/game/dyes/outfit/2slots_Duets_Pianist1.jpg",
  "/assets/game/dyes/outfit/2slots_Duets_Pianist2.jpg",
  "/assets/game/dyes/outfit/2slots_Flight_Builder.jpg",
  "/assets/game/dyes/outfit/2slots_Flight_chime.jpg",
  "/assets/game/dyes/outfit/2slots_Flight_LW.jpg",
  "/assets/game/dyes/outfit/2slots_Flight_ult.jpg",
  "/assets/game/dyes/outfit/2slots_Fortune_Snake.jpg",
  "/assets/game/dyes/outfit/2slots_Moments_monk.jpg",
  "/assets/game/dyes/outfit/2slots_Moments_Nightbird.jpg",
  "/assets/game/dyes/outfit/2slots_Moonlight_robe.jpg",
  "/assets/game/dyes/outfit/2slots_Music_pants.jpg",
  "/assets/game/dyes/outfit/2slots_Nesting_ult.jpg",
  "/assets/game/dyes/outfit/2slots_Passage_Mope.jpg",
  "/assets/game/dyes/outfit/2slots_Passage_Oddball.jpg",
  "/assets/game/dyes/outfit/2slots_Performance_modest.jpg",
  "/assets/game/dyes/outfit/2slots_Performance_storyteller.jpg",
  "/assets/game/dyes/outfit/2slots_Prophecy_fire.jpg",
  "/assets/game/dyes/outfit/2slots_Radiance_Leap.jpg",
  "/assets/game/dyes/outfit/2slots_Radiance_Provoke.jpg",
  "/assets/game/dyes/outfit/2slots_Radiance_Shaman.jpg",
  "/assets/game/dyes/outfit/2slots_Remembrance_child.jpg",
  "/assets/game/dyes/outfit/2slots_Remembrance_tiptoe.jpg",
  "/assets/game/dyes/outfit/2slots_Remembrance_warrior.jpg",
  "/assets/game/dyes/outfit/2slots_Rhythm_Actor.jpg",
  "/assets/game/dyes/outfit/2slots_Rhythm_Greeter.jpg",
  "/assets/game/dyes/outfit/2slots_Rhythm_Juggler.jpg",
  "/assets/game/dyes/outfit/2slots_Rhythm_Spin.jpg",
  "/assets/game/dyes/outfit/2slots_Style_jeans.jpg",
  "/assets/game/dyes/outfit/2slots_Style_suit.jpg",
  "/assets/game/dyes/outfit/2slots_Sunlight_dadpants.jpg",
  "/assets/game/dyes/outfit/Abyss_angler.jpg",
  "/assets/game/dyes/outfit/Assembly_chuckle.jpg",
  "/assets/game/dyes/outfit/Belonging_kid.jpg",
  "/assets/game/dyes/outfit/Bloom_gardener.jpg",
  "/assets/game/dyes/outfit/Color_DarkRainbowTunic.jpg",
  "/assets/game/dyes/outfit/Color_GaySuspenders.jpg",
  "/assets/game/dyes/outfit/Dreams_peek.jpg",
  "/assets/game/dyes/outfit/Dreams_Yeti.jpg",
  "/assets/game/dyes/outfit/Duets_Cellist1.jpg",
  "/assets/game/dyes/outfit/Duets_Cellist2.jpg",
  "/assets/game/dyes/outfit/Duets_Pianist1.jpg",
  "/assets/game/dyes/outfit/Duets_Pianist2.jpg",
  "/assets/game/dyes/outfit/Flight_Builder.jpg",
  "/assets/game/dyes/outfit/Flight_chime.jpg",
  "/assets/game/dyes/outfit/Flight_LW.jpg",
  "/assets/game/dyes/outfit/Flight_ult.jpg",
  "/assets/game/dyes/outfit/Fortune_dragon.jpg",
  "/assets/game/dyes/outfit/Fortune_muralist.jpg",
  "/assets/game/dyes/outfit/Fortune_Snake.jpg",
  "/assets/game/dyes/outfit/Mischief_Goth.jpg",
  "/assets/game/dyes/outfit/Mischief_Witch.jpg",
  "/assets/game/dyes/outfit/Moments_monk.jpg",
  "/assets/game/dyes/outfit/Moments_Nightbird.jpg",
  "/assets/game/dyes/outfit/Moonlight_robe.jpg",
  "/assets/game/dyes/outfit/Music_pants.jpg",
  "/assets/game/dyes/outfit/Nesting_ult.jpg",
  "/assets/game/dyes/outfit/Passage_Mope.jpg",
  "/assets/game/dyes/outfit/Passage_Oddball.jpg",
  "/assets/game/dyes/outfit/Performance_modest.jpg",
  "/assets/game/dyes/outfit/Performance_stagehand.jpg",
  "/assets/game/dyes/outfit/Performance_storyteller.jpg",
  "/assets/game/dyes/outfit/Prophecy_fire.jpg",
  "/assets/game/dyes/outfit/Radiance_Leap.jpg",
  "/assets/game/dyes/outfit/Radiance_Provoke.jpg",
  "/assets/game/dyes/outfit/Radiance_Shaman.jpg",
  "/assets/game/dyes/outfit/Remembrance_child.jpg",
  "/assets/game/dyes/outfit/Remembrance_tiptoe.jpg",
  "/assets/game/dyes/outfit/Remembrance_warrior.jpg",
  "/assets/game/dyes/outfit/Rhythm_Actor.jpg",
  "/assets/game/dyes/outfit/Rhythm_Greeter.jpg",
  "/assets/game/dyes/outfit/Rhythm_Juggler.jpg",
  "/assets/game/dyes/outfit/Rhythm_Spin.jpg",
  "/assets/game/dyes/outfit/Sanctuary_jelly.jpg",
  "/assets/game/dyes/outfit/Style_dress.jpg",
  "/assets/game/dyes/outfit/Style_jeans.jpg",
  "/assets/game/dyes/outfit/Style_suit.jpg",
  "/assets/game/dyes/outfit/Sunlight_dadpants.jpg",
  "/assets/game/dyes/outfit/Tournament_tunic.jpg",
  "/assets/game/dyes/outfit/Treasure_pants.jpg",
  "/assets/game/dyes/shoes/Radiance_Leaping.jpg",
  "/assets/game/dyes/shoes/Radiance_Provoking.jpg",
  "/assets/game/dyes/shoes/Treasure_boots.jpg"
];

@Component({
    selector: 'app-editor-dyes',
    templateUrl: './editor-dyes.component.html',
    styleUrls: ['./editor-dyes.component.scss'],
    standalone: true,
    imports: [ItemsComponent, ItemIconComponent]
})
export class EditorDyesComponent {
  readonly _dataService = inject(DataService);

  currentFileName = '';
  currentFileIndex = -1;

  previewFile = '';
  previewFileMap: { [file: string]: IItem } = {};

  isShowingMapped = false;
  mappedFiles: Array<{guid: string, item: IItem, url: string}> = [];
  unmappedFiles:  Array<string> = [];

  /**
   *
   */
  constructor() {
    this.mappedFiles = this._dataService.itemConfig.items.filter(item => item.dye).map(item => {
      if (item.dye && !item.dye.previewUrl && !item.dye.infoUrl) {
        console.warn('No preview or info url for:', item.guid);
      }

      return [
        item.dye?.previewUrl ? { guid: item.guid, item, url: item.dye.previewUrl } : null,
        item.dye?.infoUrl ? { guid: item.guid, item, url: item.dye.infoUrl } : null,
      ];
    }).flatMap(i => i).filter((i): i is { guid: string, item: IItem, url: string } => i !== null);

    this.unmappedFiles = fileNames.filter(f => !this.mappedFiles.some(m => m.url === f));
  }

  onItemClicked(evt: ItemClickEvent): void {
    this.previewFileMap[this.previewFile] = evt.item;
  }

  onPreviewClicked(file: string): void {
    this.previewFile = file;
  }

  export(): void {
    let csv = '';
    Object.keys(this.previewFileMap).filter(k => k).forEach(previewFile => {
      const item = this.previewFileMap[previewFile];
      csv += `${item.guid},${previewFile}\n`;
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.setAttribute('hidden', '');
    a.setAttribute('href', url);
    a.setAttribute('download', 'previews.csv');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }
}
